Completed levels 1,2 of node-fs-readfile exercise. - Irwin Chen
irwin-chen/c0322-code-solutions pull request #84
Opened 2022-05-04 20:21 UTC by irwin-chen

![Screen Shot 2022-05-04 at 1 19 37 PM](https://user-images.githubusercontent.com/95939062/166819319-021792ed-a5fb-4f89-ac3b-706b2966983a.png)

2022-05-04 22:30 UTC, thebearingedge approved these changes

2022-05-05 19:52 UTC, irwin-chen commented
https://github.com/irwin-chen/c0322-code-solutions/pull/84

2022-05-05 19:54 UTC, thebearingedge requested changes

2022-05-05 19:54 UTC, thebearingedge commented on node-fs-readfile/cat.js
> +
The array is actually redundant if you go the recursion route. Just print the data from the current readfile before continuing to the next one.

2022-05-05 19:59 UTC, thebearingedge approved these changes

2022-05-05 20:00 UTC, merged